mtx: add downlink/activateRatePlan command
jooby-dev/jooby-codec pull request #383
Opened 2024-04-26 10:17 UTC by aleks-and

2024-04-26 11:40 UTC, DeadByElpy requested changes

2024-04-29 11:33 UTC, DarkPark commented on src/mtx/commands/uplink/getCorrectTime.ts
> + * import * as getCorrectTime from 'jooby-codec/obis-observer/commands/uplink/getCorrectTime.js';
```suggestion
 * import * as getCorrectTime from 'jooby-codec/mtx/commands/uplink/getCorrectTime.js';
```

2024-04-29 11:33 UTC, DarkPark commented on src/mtx/commands/uplink/getCurrentValues.ts
> + * import * as getCurrentValues from 'jooby-codec/obis-observer/commands/uplink/getCurrentValues.js';
and here

2024-04-29 13:53 UTC, aleks-and commented on src/mtx/commands/uplink/getCurrentValues.ts
> + * import * as getCurrentValues from 'jooby-codec/obis-observer/commands/uplink/getCurrentValues.js';
done

2024-04-29 20:11 UTC, DeadByElpy approved these changes

2024-04-30 08:01 UTC, merged