rename commands and add examples
jooby-dev/jooby-codec pull request #69
Opened 2023-04-24 16:44 UTC by DarkPark

2023-04-24 18:22 UTC, DeadByElpy requested changes

2023-04-25 07:06 UTC, DarkPark commented on src/commands/uplink/CurrentMC.ts
>  import {UPLINK} from '../../constants/directions.js';
nope
it's not always a response

2023-04-25 07:07 UTC, DarkPark commented on src/commands/uplink/CurrentMC.ts
>  import {UPLINK} from '../../constants/directions.js';
it's the same for other comments

2023-04-25 07:29 UTC, DeadByElpy approved these changes

2023-04-25 07:29 UTC, merged